# TASK 1 — Creating Arrays


In [1]:
import numpy as np


In [3]:

# 1D array
arr1 = np.arange(1, 11)
print("1D Array:")
print(arr1)

# 2D array
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print("\n2D Array:")
print(arr2)

# Zeros array
zeros_array = np.zeros((4, 4))
print("\nZeros Array:")
print(zeros_array)

# Ones array
ones_array = np.ones((2, 5))
print("\nOnes Array:")
print(ones_array) 

1D Array:
[ 1  2  3  4  5  6  7  8  9 10]

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Zeros Array:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones Array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


 # Task 2 — Array Properties

In [5]:
import numpy as np

# Making a simple 2D array
numbers = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Printing the array
print("2D Array:")
print(numbers)

# 1. Shape of array
print("\nShape of array:")
print(numbers.shape)

# 2. Total elements
print("\nTotal number of elements:")
print(numbers.size)

# 3. Data type
print("\nData type of elements:")
print(numbers.dtype)

# 4. Number of dimensions
print("\nNumber of dimensions:")
print(numbers.ndim)

# 5. Importance of shape in AI
print("\nWhy shape is important in AI?")
print("Shape shows rows and columns of data.")
print("AI models need correct data shape to work properly.")
print("For example, image data and datasets must have proper dimensions.")

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Shape of array:
(3, 3)

Total number of elements:
9

Data type of elements:
int64

Number of dimensions:
2

Why shape is important in AI?
Shape shows rows and columns of data.
AI models need correct data shape to work properly.
For example, image data and datasets must have proper dimensions.


# Task 3 — Indexing 

In [6]:
import numpy as np

numbers = np.array([10, 20, 30, 40, 50, 60])

print("Array:")
print(numbers)

print("\nFirst element:")
print(numbers[0])

print("\nLast element:")
print(numbers[-1])

print("\nThird element:")
print(numbers[2])

print("\nValues greater than 30:")
print(numbers[numbers > 30])

Array:
[10 20 30 40 50 60]

First element:
10

Last element:
60

Third element:
30

Values greater than 30:
[40 50 60]


 # Task 4 — Slicing 

In [7]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])

print(a[1:5])

print(a[::-1])

print(a[::2])

b = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(b[0])

print(b[:, 1])

print(b[1:])

[2 3 4 5]
[6 5 4 3 2 1]
[1 3 5]
[1 2 3]
[2 5 8]
[[4 5 6]
 [7 8 9]]


# Task 5 — Vectorization 

In [8]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])

print("Original Array:")
print(a)

print("\nMultiply by 5:")
print(a * 5)

print("\nAdd 10:")
print(a + 10)

print("\nSquare of elements:")
print(a ** 2)

print("\nWhy vectorization is important in AI?")
print("Vectorization makes calculations faster.")
print("It helps AI models work with large data easily.")
print("It also reduces the need for loops.")

Original Array:
[1 2 3 4 5]

Multiply by 5:
[ 5 10 15 20 25]

Add 10:
[11 12 13 14 15]

Square of elements:
[ 1  4  9 16 25]

Why vectorization is important in AI?
Vectorization makes calculations faster.
It helps AI models work with large data easily.
It also reduces the need for loops.


 # Task 6 — Broadcasting

In [9]:
import numpy as np

x = np.array([[1, 2, 3],
              [4, 5, 6]])

print(x)

print(x + 10)

print(x * 2)

print("Broadcasting helps to do calculations quickly on arrays.") 

[[1 2 3]
 [4 5 6]]
[[11 12 13]
 [14 15 16]]
[[ 2  4  6]
 [ 8 10 12]]
Broadcasting helps to do calculations quickly on arrays.


# Task 7 — Matrix Addition and Subtraction 

In [10]:
import numpy as np

a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

print("Matrix A:")
print(a)

print("Matrix B:")
print(b)

print("Addition:")
print(a + b)

print("Subtraction:")
print(a - b)

Matrix A:
[[1 2]
 [3 4]]
Matrix B:
[[5 6]
 [7 8]]
Addition:
[[ 6  8]
 [10 12]]
Subtraction:
[[-4 -4]
 [-4 -4]]


 # Task 8 — Matrix Multiplication 

In [11]:
import numpy as np

a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

print(a)
print(b)

print(np.dot(a, b))

print(a.T)

print("Matrix multiplication is used in neural networks to connect layers and calculate outputs.")

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[[1 3]
 [2 4]]
Matrix multiplication is used in neural networks to connect layers and calculate outputs.


 # Task 9 — Random  

In [13]:
import numpy as np

a = np.random.randint(1, 101, (4, 4))
print(a)

b = np.random.random((3, 3))
print(b)

print("Max:", a.max())
print("Min:", a.min())
print("Average:", a.mean())

print("Random numbers are used in AI for initializing models and training data.") 

[[50  8 41 88]
 [53 45 91 64]
 [26 92 29 95]
 [72 69 63 56]]
[[0.49051085 0.86880592 0.98808211]
 [0.92041351 0.06202461 0.41958457]
 [0.70825878 0.49978285 0.6313512 ]]
Max: 95
Min: 8
Average: 58.875
Random numbers are used in AI for initializing models and training data.


# Task 10 — Student Marks Analysis

In [14]:
import numpy as np

marks = np.array([45, 78, 90, 56, 88, 34, 67, 92, 40, 81])

print("Marks:", marks)

print("Average:", marks.mean())
print("Highest:", marks.max())
print("Lowest:", marks.min())

print("Above 80:", np.sum(marks > 80))

print("Failed (below 50):", marks[marks < 50])

Marks: [45 78 90 56 88 34 67 92 40 81]
Average: 67.1
Highest: 92
Lowest: 34
Above 80: 4
Failed (below 50): [45 34 40]


 # Task 11 — Image Pixel Simulation 

In [15]:
import numpy as np

img = np.random.randint(0, 256, (5, 5))

print(img)

print("Brightest pixel:", img.max())
print("Darkest pixel:", img.min())
print("Shape:", img.shape)

print("AI reads images as numbers in a grid (array).")
print("Each number represents brightness of a pixel.")
print("AI uses these numbers to understand images.")

[[109  23 200  46  76]
 [ 95 133  93 100 116]
 [211  46  56  30 157]
 [157 101  61  92 167]
 [205   2  15 140  14]]
Brightest pixel: 211
Darkest pixel: 2
Shape: (5, 5)
AI reads images as numbers in a grid (array).
Each number represents brightness of a pixel.
AI uses these numbers to understand images.


# Task 12 — Data Normalization 

In [16]:
import numpy as np

data = np.array([10, 20, 30, 40, 50])

print("Original data:", data)

normalized = (data - data.min()) / (data.max() - data.min())

print("Normalized data:", normalized)

print("Normalization makes all values on same scale.")
print("This helps AI learn better and faster.")

Original data: [10 20 30 40 50]
Normalized data: [0.   0.25 0.5  0.75 1.  ]
Normalization makes all values on same scale.
This helps AI learn better and faster.


# Task 13 — Mini AI Dataset Task 

In [17]:
import numpy as np

data = np.array([
    [20, 20000, 0],
    [25, 30000, 1],
    [30, 40000, 1],
    [35, 50000, 0],
    [40, 60000, 1]
])

print(data)

x = data[:, 0:2]
y = data[:, 2]

print("Features:")
print(x)

print("Labels:")
print(y)

print("Average salary:", x[:, 1].mean())
print("Highest age:", x[:, 0].max())
print("Shape:", data.shape)

[[   20 20000     0]
 [   25 30000     1]
 [   30 40000     1]
 [   35 50000     0]
 [   40 60000     1]]
Features:
[[   20 20000]
 [   25 30000]
 [   30 40000]
 [   35 50000]
 [   40 60000]]
Labels:
[0 1 1 0 1]
Average salary: 40000.0
Highest age: 40
Shape: (5, 3)
