In [1]:
import numpy as np

data = np.array([
    [78, 85, 80, 90, 1],
    [45, 50, 40, 55, 0],
    [88, 92, 84, 91, 1],
    [60, 58, 65, 62, 1],
    [35, 40, 38, 45, 0],
    [95, 90, 93, 97, 1],
    [72, 75, 70, 68, 1],
    [50, 48, 52, 47, 0],
    [81, 79, 85, 88, 1],
    [42, 45, 40, 43, 0]
])

X = data[:, :-1]
y = data[:, -1]

print("Features (X):")
print(X)

print("\nLabels (y):")
print(y)

average_marks = np.mean(X)
maximum_marks = np.max(X)
minimum_marks = np.min(X)

print("\nAverage Marks:", average_marks)
print("Maximum Marks:", maximum_marks)
print("Minimum Marks:", minimum_marks)

passed_students = np.sum(y == 1)
failed_students = np.sum(y == 0)

print("\nNumber of Passed Students:", passed_students)
print("Number of Failed Students:", failed_students)

above_80 = X[X > 80]

print("\nMarks Above 80:")
print(above_80)

below_50 = X[X < 50]

print("\nMarks Below 50:")
print(below_50)

X_normalized = (X - np.min(X)) / (np.max(X) - np.min(X))

print("\nNormalized Dataset:")
print(X_normalized)

average_per_student = np.mean(X, axis=1)

predictions = np.where(average_per_student >= 60, 1, 0)

print("\nPredicted Results:")
print(predictions)

accuracy = np.mean(predictions == y) * 100

print("\nPrediction Accuracy:", accuracy, "%")

Features (X):
[[78 85 80 90]
 [45 50 40 55]
 [88 92 84 91]
 [60 58 65 62]
 [35 40 38 45]
 [95 90 93 97]
 [72 75 70 68]
 [50 48 52 47]
 [81 79 85 88]
 [42 45 40 43]]

Labels (y):
[1 0 1 1 0 1 1 0 1 0]

Average Marks: 66.025
Maximum Marks: 97
Minimum Marks: 35

Number of Passed Students: 6
Number of Failed Students: 4

Marks Above 80:
[85 90 88 92 84 91 95 90 93 97 81 85 88]

Marks Below 50:
[45 40 35 40 38 45 48 47 42 45 40 43]

Normalized Dataset:
[[0.69354839 0.80645161 0.72580645 0.88709677]
 [0.16129032 0.24193548 0.08064516 0.32258065]
 [0.85483871 0.91935484 0.79032258 0.90322581]
 [0.40322581 0.37096774 0.48387097 0.43548387]
 [0.         0.08064516 0.0483871  0.16129032]
 [0.96774194 0.88709677 0.93548387 1.        ]
 [0.59677419 0.64516129 0.56451613 0.53225806]
 [0.24193548 0.20967742 0.27419355 0.19354839]
 [0.74193548 0.70967742 0.80645161 0.85483871]
 [0.11290323 0.16129032 0.08064516 0.12903226]]

Predicted Results:
[1 0 1 1 0 1 1 0 1 0]

Prediction Accuracy: 100.0 %
